'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { api, login, logout } from '../lib/api'
import { Eye, EyeOff, LockKeyhole, Mail, Plus, WalletCards, TrendingDown, CalendarDays, LogOut, RefreshCw, Trash2, CheckCircle2 } from 'lucide-react'

type User={id:string;name:string;email:string}
type Dashboard={income:{recurring:string;extra:string;total:string};outflow:{expenses:string;installments:string;total:string};balance:string;upcomingInstallments:any[];upcomingExpenses:any[]}
const money=(v:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))
const today=()=>new Date().toISOString().slice(0,10)

export default function Page(){
 const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showPassword,setShowPassword]=useState(false)
 const [dash,setDash]=useState<Dashboard|null>(null); const [section,setSection]=useState<'dashboard'|'income'|'receipts'|'expenses'|'debts'>('dashboard'); const [rows,setRows]=useState<any[]>([]); const [modal,setModal]=useState<string|null>(null); const [saving,setSaving]=useState(false)
 const [form,setForm]=useState<any>({description:'',amount:'',expectedDay:'5',startDate:today(),receivedAt:today(),expenseDate:today(),dueDate:today(),originalAmount:'',installmentCount:'2',firstDueDate:today(),interestAmount:'0'})
 const loadDashboard=async()=>{const r=await api<any>('dashboard');setDash(r.data)}
 const loadSection=async(s=section)=>{if(s==='income')setRows((await api<any>('income')).data);if(s==='receipts')setRows((await api<any>('receipts')).data);if(s==='expenses')setRows((await api<any>('expenses')).data);if(s==='debts')setRows((await api<any>('debts')).data)}
 useEffect(()=>{api<any>('auth/me').then(r=>{setUser(r.user);setLoading(false);return loadDashboard()}).catch(()=>setLoading(false))},[])
 useEffect(()=>{if(user&&section!=='dashboard')loadSection(section)},[user,section])
 async function doLogin(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setLoading(true);const f=new FormData(e.currentTarget);try{const r=await login(String(f.get('email')),String(f.get('password')));setUser(r.user);await loadDashboard()}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{if(modal==='income')await api('income',{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount),expectedDay:Number(form.expectedDay)})});if(modal==='receipts')await api('receipts',{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount)})});if(modal==='expenses')await api('expenses',{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount)})});if(modal==='debts')await api('debts',{method:'POST',body:JSON.stringify({...form,originalAmount:Number(form.originalAmount),installmentCount:Number(form.installmentCount),interestAmount:Number(form.interestAmount||0)})});setModal(null);setForm({description:'',amount:'',expectedDay:'5',startDate:today(),receivedAt:today(),expenseDate:today(),dueDate:today(),originalAmount:'',installmentCount:'2',firstDueDate:today(),interestAmount:'0'});await loadDashboard();if(section!=='dashboard')await loadSection()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function remove(type:string,id:string){if(!confirm('Excluir este registro?'))return;try{await api(`${type}/${id}`,{method:'DELETE'});await loadDashboard();await loadSection()}catch(e:any){setError(e.message)}}
 if(loading&&!user)return <main className="center-screen"><div className="spinner"/></main>
 if(!user)return <main className="login-page"><section className="login-card"><div className="login-logo mariofin-logo">MF</div><div className="form-heading"><p className="form-eyebrow">MARIOFIN</p><h1>Login</h1><p>Seu controle financeiro, em um só lugar.</p></div><form className="login-form" onSubmit={doLogin}><div className="field-group"><label>E-mail</label><div className="input-with-icon"><Mail size={18}/><input name="email" type="email" placeholder="seuemail@exemplo.com" required/></div></div><div className="field-group"><label>Senha</label><div className="input-with-icon"><LockKeyhole size={18}/><input name="password" type={showPassword?'text':'password'} placeholder="Sua senha" required/><button type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{error&&<div className="error-box">{error}</div>}<button className="login-button" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form></section></main>
 const cards=[['Saldo previsto',money(dash?.balance),'balance'],['Entradas',money(dash?.income.total),'income'],['Despesas',money(dash?.outflow.expenses),'expense'],['Parcelas',money(dash?.outflow.installments),'debt']]
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>MF</span><div><strong>MarioFin</strong><small>Gestão financeira</small></div></div><nav>{[['dashboard','Visão geral'],['income','Rendas'],['receipts','Entradas extras'],['expenses','Despesas'],['debts','Dívidas e parcelas']].map(([id,label])=><button className={section===id?'active':''} onClick={()=>setSection(id as any)} key={id}>{label}</button>)}</nav><button className="logout" onClick={async()=>{await logout();setUser(null)}}><LogOut size={17}/> Sair</button></aside><section className="content"><header className="topbar"><div><span className="eyebrow">PAINEL FINANCEIRO</span><h2>{section==='dashboard'?'Visão geral':section==='income'?'Rendas mensais':section==='receipts'?'Entradas extras':section==='expenses'?'Despesas':'Dívidas e parcelas'}</h2></div><button className="refresh" onClick={()=>{loadDashboard();loadSection()}}><RefreshCw size={16}/> Atualizar</button></header>{error&&<div className="error-box">{error}</div>}
 {section==='dashboard'&&<><div className="cards">{cards.map(([t,v,c])=><article className="metric" key={t}><span>{t}</span><strong className={c}>{v}</strong></article>)}</div><div className="grid-two"><article className="panel"><div className="panel-title"><div><span>PRÓXIMOS COMPROMISSOS</span><h3>Parcelas</h3></div><CalendarDays size={20}/></div>{dash?.upcomingInstallments?.length?dash.upcomingInstallments.map((x:any)=><div className="list-row" key={x.id}><div><strong>{x.debt?.description}</strong><small>Parcela {x.installmentNumber}/{x.debt?.installmentCount} • {new Date(x.dueDate).toLocaleDateString('pt-BR')}</small></div><b>{money(x.amount)}</b></div>):<p className="empty">Nenhuma parcela próxima.</p>}</article><article className="panel"><div className="panel-title"><div><span>SAÍDAS</span><h3>Despesas</h3></div><TrendingDown size={20}/></div>{dash?.upcomingExpenses?.length?dash.upcomingExpenses.map((x:any)=><div className="list-row" key={x.id}><div><strong>{x.description}</strong><small>{new Date(x.dueDate||x.expenseDate).toLocaleDateString('pt-BR')} • {x.status}</small></div><b>{money(x.amount)}</b></div>):<p className="empty">Nenhuma despesa no período.</p>}</article></div></>}
 {section!=='dashboard'&&<><div className="section-actions"><button className="primary" onClick={()=>setModal(section)}><Plus size={17}/> Adicionar</button></div><article className="panel table-panel">{rows.length===0?<p className="empty">Nenhum registro cadastrado.</p>:<div className="data-list">{rows.map((x:any)=><div className="data-row" key={x.id}><div><strong>{x.description}</strong><small>{section==='debts'?`${x.installmentCount} parcelas • ${x.status}`:section==='income'?`Recebe dia ${x.expectedDay} • ${x.recurrence}`:new Date(x.receivedAt||x.expenseDate).toLocaleDateString('pt-BR')}</small></div><div className="row-right"><b>{money(x.amount||x.totalAmount)}</b><button onClick={()=>remove(section==='income'?'income':section==='receipts'?'receipts':section==='expenses'?'expenses':'debts',x.id)}><Trash2 size={16}/></button></div></div>)}</div>}</article></>}
 </section>{modal&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setModal(null)}><form className="modal" onSubmit={save}><div className="modal-head"><div><span>NOVO REGISTRO</span><h3>{modal==='income'?'Renda mensal':modal==='receipts'?'Entrada extra':modal==='expenses'?'Despesa':'Dívida'}</h3></div><button type="button" onClick={()=>setModal(null)}>×</button></div><label>Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label>{modal==='debts'?<><label>Valor bruto<input type="number" step="0.01" value={form.originalAmount} onChange={e=>setForm({...form,originalAmount:e.target.value})} required/></label><label>Juros<input type="number" step="0.01" value={form.interestAmount} onChange={e=>setForm({...form,interestAmount:e.target.value})}/></label><label>Número de parcelas<input type="number" min="1" value={form.installmentCount} onChange={e=>setForm({...form,installmentCount:e.target.value})} required/></label><label>Primeiro vencimento<input type="date" value={form.firstDueDate} onChange={e=>setForm({...form,firstDueDate:e.target.value})} required/></label></>:<><label>Valor<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label>{modal==='income'?<><label>Dia do pagamento<input type="number" min="1" max="31" value={form.expectedDay} onChange={e=>setForm({...form,expectedDay:e.target.value})}/></label><label>Início<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label></>:modal==='receipts'?<label>Data recebida<input type="date" value={form.receivedAt} onChange={e=>setForm({...form,receivedAt:e.target.value})}/></label>:<><label>Data da despesa<input type="date" value={form.expenseDate} onChange={e=>setForm({...form,expenseDate:e.target.value})}/></label><label>Vencimento<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label></>}</>}<button className="login-button" disabled={saving}>{saving?'Salvando...':<><CheckCircle2 size={17}/> Salvar</>}</button></form></div>}</main>
}
